apiVersion: v1
kind: Service
metadata:
  labels:
    app: arl-udaconnect-persons-api
  name: arl-udaconnect-persons-api
spec:
  ports:
  - name: 5000-30002
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30002
  selector:
    app: arl-udaconnect-persons-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: arl-udaconnect-persons-api
  name: arl-udaconnect-persons-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arl-udaconnect-persons-api
  template:
    metadata:
      labels:
        app: arl-udaconnect-persons-api
    spec:
      containers:
      - image: arlisaputro/person-api:v1
        name: arl-udaconnect-persons-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
